[project]
name = "desafio-estagio-magalu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.142.2",
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "sqlalchemy>=2.1.3",
    "uvicorn>=0.54.0",
]

[tool.pytest.ini_options]
pythonpath = ["src"]